### PR TITLE
Fixed: Issue 172: Default chart types for Topic and Theme filters

### LINKED ISSUE #172: Display related chart based on selection from homepage
When clicking on an button/tile on the homepage that takes users to filtered datasets, the corresponding Data Analytics chart should display. Currently, the Repositories chart defaults to "Repositories".

When clicking on:
- Themes button > "Themes" graph 
- Categories button > "Topics" graph

### LINKED ISSUE #188: Information and/or Email icons appear and may not have hoverable data
Discussed at BRC tech call on MAR 19 2026 in the chat

The (i) icon here implies there is a hoverable value but this doesn't have one (the email icon does have a value, though it's "email not provided") .

### PR DESCRIPTION
**Pull request by valerie-autumn-skye**
## What does this do

- Changes default chart to **Themes** when filtering by `theme` (see example in Issue #172).
- Changes default chart to **Topics** when filtering by `topic` (see example in Issue #172).
- Adjusts author contact and affiliation visibility based on availability of information (see example in Issue #188).

## Related Issues

Fixes #172
Fixes #188

## Screenshots

theme_filter_chart

---

Before author contact and affiliation change:

before_change

After author contact and affiliation change:

after_change

## Acceptance

Add an 'x' to the boxes below if they are complete
- [x] My changes work as expected locally
- [x] My changes are related to existing issues or other approved work
- [ ] I updated the Changelog (if applicable)
- [ ] I added tests with appropriate coverage and verified they all pass (if applicable)
- [ ] I updated user documentation (if applicable)

### CODE REVIEW

**Comment by ianderthal** [comment]
@valerie-autumn-skye The Theme/Topic charts displaying on the Search Results page when making a selection from the homepage work great. While on the Search page, seeing the charts update when filters are changed is great but can give users the impression that search results are also changing when checkboxes are being toggled (when results are not updating).

What do you think of the interaction where the chart switches (based on the filter selections) when the "Filter Results" button is clicked instead of on checkbox toggle?

**Comment by valerie-autumn-skye** [comment]
> @valerie-autumn-skye The Theme/Topic charts displaying on the Search Results page when making a selection from the homepage work great. While on the Search page, seeing the charts update when filters are changed is great but can give users the impression that search results are also changing when checkboxes are being toggled (when results are not updating).
> 
> What do you think of the interaction where the chart switches (based on the filter selections) when the "Filter Results" button is clicked instead of on checkbox toggle?

@hplahar Please add this discussion topic to the agenda for Thursday 4/23.

File: api/server.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ const schemaRoutes = require('./app/routes/schema.routes');
 const app = express();
 
 var corsOptions = {
-  origin: [process.env.BIOENERGY_ORG_CLIENT_URI, "https://api.bioenergy.org", "https://bioenergy.org", "https://www.bioenergy.org"]
+  origin: [process.env.BIOENERGY_ORG_CLIENT_URI, "https://api.bioenergy.org", "http://localhost:3000", "http://localhost:8081", "http://localhost:8080", "https://bioenergy.org", "https://www.bioenergy.org"]
```
Comment (ianderthal) [inline api/server.js]: Per tech meeting 04/23, we'll try to troubleshoot errors to avoid committing localhost references into the code.

**Comment by valerie-autumn-skye** [comment]
Rebased onto `main` to remove CORS changes.

File: api/server.js (hunk 1 above)
Comment (valerie-autumn-skye) [reply api/server.js]: Rebased onto `main` to remove CORS commit.
